# Generated by Django 5.1.6 on 2025-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv_file_name',
            field=models.CharField(max_length=255),
        ),
    ]
